### ISSUE TITLE
High quality gifs

### ISSUE THREAD

**Issue by ryanraposo** [warmachine028/Better-Calculator#14]
So, about gifs!

## Capturing

[ScreenToGif](https://www.screentogif.com/) is great. If you're able to use it (Windows), there are some settings I'd recommend.

<details><summary>Recommended Settings</summary>

### Application:

(If it doesn't feel right, try disabling 'Only capture when something changes')

![screentogif-settings](https://user-images.githubusercontent.com/38861352/104683448-ed50b400-56c4-11eb-9bea-7e9ca82ea5b3.png)

### Toolbar:

![screentogif-panel](https://user-images.githubusercontent.com/38861352/104683581-330d7c80-56c5-11eb-9bbb-cbe87af46ba8.png)

### Editor:

![screentogif-editor](https://user-images.githubusercontent.com/38861352/104684042-276e8580-56c6-11eb-9493-99000d52c23a.png)

Let me know if you can't use ScreenToGif, or you have any other questions! Thanks again for reaching out. Always feel free.

</details>

## Checklist

Here are some README items that could use great gifs to show-off or explain the calculator's features. 

- [x] Switching themes
- [x] Basic usage
- [x] Editing attributes

Note: we could decide on a final list below, and then check them off as we add them to the `main` branch. :)

**Comment by warmachine028** [comment]
thank you so much for replying . It was very helpful :)

**Comment by ryanraposo** [comment]
> 
> 
> thank you so much for replying . It was very helpful :)

Of course! Do you want to use this issue to make a list of demo gifs we should add? I'll update the post with examples, just to illustrate the format--nothing final!

**Comment by ryanraposo** [comment]
@warmachine028 updated the issue with an example list. What would you like to showcase most in some gifs?

**Comment by warmachine028** [comment]
> > thank you so much for replying . It was very helpful :)
> 
> Of course! Do you want to use this issue to make a list of demo gifs we should add? I'll update the post with examples, just to illustrate the format--nothing final!

Yes it would be very helpful

**Comment by warmachine028** [comment]
> @warmachine028 updated the issue with an example list. What would you like to showcase most in some gifs?

I would like to showcase how to make new themes in "themes.json"
